force-app/main/default/objects/Lead/fields/Totale_Prijs__c.field-meta.xml
<CustomField>
    <fullName>Totale_Prijs__c</fullName>
    <description>Filled by Declarative lookup tool</description>
    <label>Totaal Excl. BTW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/Lead_Product__c.object-meta.xml
<CustomObject>
    <label>Lead Product</label>
    <nameField>
        <label>Lead Product Naam</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Producten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Product__c/fields/Aantal__c.field-meta.xml
<CustomField>
    <fullName>Aantal__c</fullName>
    <description>The quantity of the choosen product.</description>
    <label>Aantal</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Breedte_cm__c.field-meta.xml
<CustomField>
    <fullName>Breedte_cm__c</fullName>
    <description>Width of the carpet. Used to calculate M2 of carpet if Lenght and Width are both filled.</description>
    <label>Breedte (cm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for quote request from website. Will be converted to Opportunity Line Items</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Producten</relationshipLabel>
    <relationshipName>Lead_Producten</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Lengte_cm__c.field-meta.xml
<CustomField>
    <fullName>Lengte_cm__c</fullName>
    <description>Length of the carpet. Used to calculate M2 of carpet if Lenght and Width are both filled.</description>
    <label>Lengte (cm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Oppervlakte_m__c.field-meta.xml
<CustomField>
    <fullName>Oppervlakte_m__c</fullName>
    <description>Either filled in directly by w2l form or calculated based on length * width or based on diameter calculations.</description>
    <label>Oppervlakte (m²)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product requested to be quoted.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lead Producten</relationshipLabel>
    <relationshipName>Lead_Producten</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Regiotoeslag__c.field-meta.xml
<CustomField>
    <fullName>Regiotoeslag__c</fullName>
    <description>Gebruikt voor berekeningen</description>
    <label>Regiotoeslag</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <formula>TEXT(Product__r.Segment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Selectie_Producttype__c.field-meta.xml
<CustomField>
    <fullName>Selectie_Producttype__c</fullName>
    <description>Used for flow to check product</description>
    <formula>TEXT( Product__r.Selectie_Producttype__c)</formula>
    <label>Selectie Producttype</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Totale_Prijs__c.field-meta.xml
<CustomField>
    <fullName>Totale_Prijs__c</fullName>
    <description>Gevuld door flow.</description>
    <label>Totaal Excl BTW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead_Product__c/fields/Verkoopprijs__c.field-meta.xml
<CustomField>
    <fullName>Verkoopprijs__c</fullName>
    <description>The unit price given to the product.</description>
    <label>Verkoopprijs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prijsmanagement__c/Prijsmanagement__c.object-meta.xml
<CustomObject>
    <label>Prijsmanagement</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Prijsmanagementnummer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prijsmanagement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prijsmanagement__c/fields/Eenheidsprijs__c.field-meta.xml
<CustomField>
    <fullName>Eenheidsprijs__c</fullName>
    <description>Prijs that will be used on quantity</description>
    <label>Eenheidsprijs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prijsmanagement__c/fields/Geldig_tot__c.field-meta.xml
<CustomField>
    <fullName>Geldig_tot__c</fullName>
    <description>End date of the price management</description>
    <label>Geldig tot</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prijsmanagement__c/fields/Geldig_vanaf__c.field-meta.xml
<CustomField>
    <fullName>Geldig_vanaf__c</fullName>
    <description>Start date that the prijs management starts</description>
    <label>Geldig vanaf</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prijsmanagement__c/fields/Minimale_prijs__c.field-meta.xml
<CustomField>
    <fullName>Minimale_prijs__c</fullName>
    <description>The start price the product will be mimimaly sold for.</description>
    <label>Minimale prijs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prijsmanagement__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Product the price mangement is related to</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Prijsmanagement</relationshipLabel>
    <relationshipName>Prijsmanagement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Used for linking product and service areas</description>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Selectie_Producttype__c.field-meta.xml
<CustomField>
    <fullName>Selectie_Producttype__c</fullName>
    <label>Selectie Producttype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primair</fullName>
            </value>
            <value>
                <fullName>Pakket</fullName>
            </value>
            <value>
                <fullName>Optie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Wasserij_item__c/Wasserij_item__c.object-meta.xml
<CustomObject>
    <label>Wasserij item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Naam van Wasserij item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wasserij items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wasserij_item__c/fields/Aantal__c.field-meta.xml
<CustomField>
    <fullName>Aantal__c</fullName>
    <label>Aantal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wasserij_item__c/fields/Breedte__c.field-meta.xml
<CustomField>
    <fullName>Breedte__c</fullName>
    <label>Breedte (cm)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wasserij_item__c/fields/Lengte__c.field-meta.xml
<CustomField>
    <fullName>Lengte__c</fullName>
    <label>Lengte (cm)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wasserij_item__c/fields/Oppervlakte_m__c.field-meta.xml
<CustomField>
    <fullName>Oppervlakte_m__c</fullName>
    <description>Either filled in directly by w2l form or calculated based on length * width or based on diameter calculations.</description>
    <label>Oppervlakte (m²)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wasserij_item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Wasserij items</relationshipLabel>
    <relationshipName>Wasserij_items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wasserij_item__c/fields/Regiotoeslag__c.field-meta.xml
<CustomField>
    <fullName>Regiotoeslag__c</fullName>
    <label>Regiotoeslag</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Wasserij_item__c/fields/Selectie_Producttype__c.field-meta.xml
<CustomField>
    <fullName>Selectie_Producttype__c</fullName>
    <description>Used for flow criteria filter</description>
    <formula>TEXT(Product__r.Selectie_Producttype__c )</formula>
    <label>Selectie Producttype</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wasserij_item__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <label>SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wasserij_item__c/fields/Totale_Prijs__c.field-meta.xml
<CustomField>
    <fullName>Totale_Prijs__c</fullName>
    <description>Gevuld door flow.</description>
    <label>Totale Prijs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Wasserij_item__c/fields/Verkoopprijs__c.field-meta.xml
<CustomField>
    <fullName>Verkoopprijs__c</fullName>
    <label>Verkoopprijs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Wasserij_item__c/fields/Werk_Order__c.field-meta.xml
<CustomField>
    <fullName>Werk_Order__c</fullName>
    <label>Werk Order</label>
    <referenceTo>Werk_Order__c</referenceTo>
    <relationshipLabel>Wasserij items</relationshipLabel>
    <relationshipName>Wasserij_items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Werk_Order__c/Werk_Order__c.object-meta.xml
<CustomObject>
    <label>Werk Order</label>
    <nameField>
        <displayFormat>WB-{00000}</displayFormat>
        <label>Werk Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Werk Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Werk_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.PersonContactId</field>
            <operation>equals</operation>
            <valueField>$Source.Contactpersoon__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Werk Orders</relationshipLabel>
    <relationshipName>Werk_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Werk_Order__c/recordTypes/Wasserij.recordType-meta.xml
<RecordType>
    <fullName>Wasserij</fullName>
    <active>true</active>
    <description>Gebruik deze voor items die in de onze wasserij worden gereinigd.</description>
    <label>Wasserij</label>
</RecordType>

force-app/main/default/classes/PricingService_Test_Fixed.cls
@isTest
private class PricingService_Test_Fixed {

    @testSetup
    static void makeData(){
        Product2 vloerkleedProduct = new Product2(
            Name='Test Vloerkleed',
            ProductCode='VLRK-TEST',
            IsActive=true,
            Segment__c = 'Wasserij',
            Selectie_Producttype__c = 'Primair'
        );
        insert vloerkleedProduct;

        Prijsmanagement__c vloerkleedRule = new Prijsmanagement__c(
            Product__c = vloerkleedProduct.Id,
            Eenheidsprijs__c = 24.38,
            Minimale_prijs__c = 90.91,
            Geldig_vanaf__c = Date.today().addDays(-1),
            Geldig_tot__c = Date.today().addDays(365)
        );
        insert vloerkleedRule;

        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = vloerkleedProduct.Id,
            UnitPrice = 1.00,
            IsActive = true
        );
        insert standardPrice;

        Lead testLead = new Lead(LastName='Test Klant', Company='Test BV');
        insert testLead;
        
        // Setup voor Wasserij_Item tests
        Account testAccount = new Account(Name='Test Account');
        insert testAccount;
        
        Werk_Order__c testWerkOrder = new Werk_Order__c(Account__c = testAccount.Id);
        insert testWerkOrder;
    }

    @isTest
    static void testLeadProductBasicPricing() {
        Lead testLead = [SELECT Id FROM Lead WHERE LastName='Test Klant' LIMIT 1];
        Product2 vloerkleedProduct = [SELECT Id FROM Product2 WHERE ProductCode = 'VLRK-TEST' LIMIT 1];
        
        Lead_Product__c lp = new Lead_Product__c(
            Lead__c = testLead.Id, 
            Product__c = vloerkleedProduct.Id, 
            SKU__c = 'VLRK-TEST', 
            Lengte_cm__c = 100, 
            Breedte_cm__c = 100
        );
        
        Test.startTest();
        insert lp;
        Test.stopTest();
        
        Lead_Product__c result = [SELECT Totale_Prijs__c, Verkoopprijs__c FROM Lead_Product__c WHERE Id =: lp.Id];
        System.assertNotEquals(null, result.Totale_Prijs__c, 'Totale_Prijs should be calculated');
        System.assertNotEquals(null, result.Verkoopprijs__c, 'Verkoopprijs should be calculated');
    }

    @isTest
    static void testLeadProductRegioToeslag() {
        Lead testLead = [SELECT Id FROM Lead WHERE LastName='Test Klant' LIMIT 1];
        Product2 vloerkleedProduct = [SELECT Id FROM Product2 WHERE ProductCode = 'VLRK-TEST' LIMIT 1];
        
        // Update Lead met Amsterdam postcode voor regiotoeslag
        testLead.PostalCode = '1012 AB';
        update testLead;
        
        Test.startTest();
        
        Lead_Product__c leadProduct = new Lead_Product__c(
            Lead__c = testLead.Id,
            Product__c = vloerkleedProduct.Id,
            SKU__c = 'VLRK-TEST',
            Aantal__c = 2
        );
        
        insert leadProduct;
        
        Test.stopTest();
        
        Lead_Product__c result = [
            SELECT Verkoopprijs__c, Totale_Prijs__c, Regiotoeslag__c, Aantal__c
            FROM Lead_Product__c 
            WHERE Id = :leadProduct.Id
        ];
        
        // Basic validation
        System.assertNotEquals(null, result.Verkoopprijs__c, 'Verkoopprijs should be calculated');
        System.assertNotEquals(null, result.Totale_Prijs__c, 'Totale_Prijs should be calculated');
        
        // Basic validation: Totale_Prijs should be Verkoopprijs * Aantal  
        if (result.Verkoopprijs__c != null && result.Aantal__c != null) {
            Decimal expectedTotal = result.Verkoopprijs__c * result.Aantal__c;
            System.assertEquals(expectedTotal.setScale(2), result.Totale_Prijs__c.setScale(2), 
                               'Totale_Prijs should equal Verkoopprijs * Aantal');
        }
    }

    @isTest
    static void testLeadProductCrossItemUpdates() {
        Lead testLead = [SELECT Id FROM Lead WHERE LastName='Test Klant' LIMIT 1];
        Product2 vloerkleedProduct = [SELECT Id FROM Product2 WHERE ProductCode = 'VLRK-TEST' LIMIT 1];
        
        // Create eerste product
        Lead_Product__c firstProduct = new Lead_Product__c(
            Lead__c = testLead.Id,
            Product__c = vloerkleedProduct.Id,
            SKU__c = 'VLRK-TEST-1',
            Lengte_cm__c = 100,
            Breedte_cm__c = 100  // 1m²
        );
        insert firstProduct;
        
        Test.startTest();
        
        // Create tweede product - dit zou cross-item updates moeten triggeren
        Lead_Product__c secondProduct = new Lead_Product__c(
            Lead__c = testLead.Id,
            Product__c = vloerkleedProduct.Id,
            SKU__c = 'VLRK-TEST-2',
            Lengte_cm__c = 200,
            Breedte_cm__c = 200  // 4m²
        );
        insert secondProduct;
        
        Test.stopTest();
        
        // Query alle producten voor deze Lead
        List<Lead_Product__c> allProducts = [
            SELECT Id, SKU__c, Oppervlakte_m__c, Aantal__c, Verkoopprijs__c 
            FROM Lead_Product__c 
            WHERE Lead__c = :testLead.Id
        ];
        
        // Verify beide producten bestaan
        System.assertEquals(2, allProducts.size(), 'Should have 2 Lead Products');
        
        // Verify oppervlakte berekening
        for (Lead_Product__c lp : allProducts) {
            if (lp.Oppervlakte_m__c != null) {
                System.assertEquals(lp.Oppervlakte_m__c, lp.Aantal__c, 'Aantal should equal Oppervlakte for carpets');
            }
        }
    }

    @isTest
    static void testWasserijItemBasicPricing() {
        Product2 vloerkleedProduct = [SELECT Id FROM Product2 WHERE ProductCode = 'VLRK-TEST' LIMIT 1];
        Werk_Order__c testWerkOrder = [SELECT Id FROM Werk_Order__c LIMIT 1];
        
        // Maak Wasserij Item aan (vloerkleed) - ZONDER SKU__c
        Wasserij_Item__c wi = new Wasserij_Item__c(
            Werk_Order__c = testWerkOrder.Id,
            Product__c = vloerkleedProduct.Id,
            Lengte__c = 200,
            Breedte__c = 300
        );

        Test.startTest();
        insert wi;
        Test.stopTest();

        Wasserij_Item__c result = [
            SELECT Verkoopprijs__c, Totale_Prijs__c, Oppervlakte_m__c, Aantal__c
            FROM Wasserij_Item__c 
            WHERE Id = :wi.Id
        ];
        
        System.assertNotEquals(null, result.Verkoopprijs__c, 'Verkoopprijs should be calculated');
        System.assertNotEquals(null, result.Totale_Prijs__c, 'Totale_Prijs should be calculated');
    }
}